apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-secret-b2.yaml
  - external-secret-pg.yaml
  - objectstore-b2.yaml
  - cnpg-cluster.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/name: jobtracker
  app.kubernetes.io/component: application
  app.kubernetes.io/part-of: jobtracker
