apiVersion: v1
kind: Service
metadata:
  name: jobtracker
  namespace: jobtracker
spec:
  selector:
    app.kubernetes.io/name: jobtracker
    app.kubernetes.io/component: server
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
